### ISSUE TITLE
Use ProtoBuf as data serialization when communicating between peers

### ISSUE THREAD

**Issue by vekexasia** [RiseVision/rise-node#122]
Communication between peers should leverage protobuf to enhance efficiency.

JSON is easier but still it adds a lot of boilerplate that will count when a lot of transactions are sent through the network.

A good TypeScript supported implementation is available here: https://github.com/dcodeIO/ProtoBuf.js/

**Comment by mcanever** [comment]
## Initial Analysis

As discussed with @vekexasia, nodes should keep compatibility with existing JSON-based transport API. 
For this reason, the proposed approach is to create a new API branch, specifically `v2/peer/...` working with protobuf instead of JSON.
Apart from implementing the various message types, the main challenges I see for this refactoring are:

- Making sure that, when a request is made to a peer, there is local awareness in the code of which response type is expected: if JSON can be deserialized with a simple `JSON.parse()`, protobuf requires a `proto` definition to deserialize any message.
- Keeping the code clean and well structured while maintaining compatibility with JSON

### Tentative todolist

- [x]  Implement the new API endpoints
    - [x] Modify express setUp to work with binary data on the new API branch: `AppManager.initExpress()`
    - [x] To avoid code duplication, isolate logic from API decorators in `apis/transportAPI.ts`. As an alternative, if possible, decorate class to use same logic to obtain data to return via ProtoBuf serialization.
    - [x] Implement ProtoBuf message types and serialization for all transport API endpoints (RESPONSE):
        - [ ] ~~`GET /peer/height`~~
        - [ ] ~~`GET /peer/ping`~~
        - [x] `GET /peer/list`
        - [x] `GET /peer/signatures`
        - [x] `POST /peer/signatures` (needs proto for response and request)
        - [x] `GET /peer/transactions`
        - [x] `POST /peer/transactions` (needs proto for response and request)
        - [x] `GET /peer/blocks`
        - [x] `POST /peer/blocks` (needs proto for response and request)
        - [x] `GET /peer/blocks/common`
- [x] Implement actual peer-to-peer communication using the new API
    - [x] ~~Add a header to peers to state that ProtoBuf API is supported~~ ==> Peer version is enough
    - [ ] ~~Add a flag to `PeerType` to remember that a specific peer supports ProtoBuf API (what about `maxAPIVersion`, with default to 1 if header not set by the peer ?)~~
    - [x] Refactor `TransportModule.getFromPeer()` so that it switches between JSON and ProtoBuf API, depending on the Peer's headers. Ideally, serialization and deserialization should be transparent to methods calling `getFromPeer()`, as this is the only point in the code making HTTP requests.
    - [x] Check each existing call to `TransportModule.getFromPeer()` and make sure it's compliant with ProtoBuf. 
           Calls to check: 
         - [x] `PeerLogic.makeRequest()`
         - [x] `PeerLogic.pingAndUpdate()`
         - [x] `LoaderModule.loadSignatures()`
         - [x] `LoaderModule.loadTransactions()`
         - [x] `TransportModule.getFromRandomPeer()`
- [x] Test
    - [x] Unit tests for new logic
    - [x] Integration tests for new endpoints
    - [x] DevNet testing, ideally with mixed versions of the node (JSON+ProtoBuf)

**Comment by vekexasia** [comment]
:+1: @mcanever . Just a couple of notes.

There is no need for a new header to be added as we can use peer version to know if it supports protobuf (or not).
The same thing goes for the PeerType addition you're proposing.

OT: We should also investigate if we could/should give priority to peers with protobuf version.

I'm unfamiliar with protobuf but will we have the ability to have some kind of versioning of every .proto file so that if we add a new field in a future release then older nodes won't just crash?

**Comment by roosmaa** [comment]
*Just a random drive-by engagement, I might not have enough background information..*

Will the actual API differ or will it mirror the existing one? If it mirrors the existing one, then the HTTP `Accept` header could be used to indicate that the client prefers protobuf reply. Would mean that the new `/v2` prefix wouldn't be needed (yet).
